update to 4.7
Signed-off-by: David Massey <David.Massey@ibm.com>

diff --git a/cp4d/cp4d-cloud-pak-deployer-pipeline.yaml b/cp4d/cp4d-cloud-pak-deployer-pipeline.yaml
--- a/cp4d/cp4d-cloud-pak-deployer-pipeline.yaml
+++ b/cp4d/cp4d-cloud-pak-deployer-pipeline.yaml
@@ -529,6 +529,17 @@ spec:
           ]
         }
       default: "xsmall"
+    - name: wkc-state
+      type: string
+      description: |
+        Do you want to install watson knowledge catalog?
+        {
+          "options": [
+            {"text": "No","value": "removed", "default": "true"},
+            {"text": "Yes","value": "installed"}
+          ]
+        }
+      default: "removed"
     - name: wkc-size
       type: string
       description: |
@@ -541,17 +552,6 @@ spec:
           ]
         }
       default: "small"
-    - name: wkc-state
-      type: string
-      description: |
-        Do you want to install watson knowledge catalog?
-        {
-          "options": [
-            {"text": "No","value": "removed", "default": "true"},
-            {"text": "Yes","value": "installed"}
-          ]
-        }
-      default: "removed"
     - name: wkc-options-core-only
       type: string
       description: |
@@ -856,12 +856,15 @@ spec:
             description: The key to use for the secret
             type: string
         steps:
-          - image: ubuntu
+          - image: docker
 
             script: |
               if [ "$(params.ibm-entitlement-key)" != "false" ]; then
                 echo "user provided key - $(params.ibm-entitlement-key)"
                 printf "$(params.ibm-entitlement-key)" | tee $(results.key.path)
+
+                echo "testing key for cp.icr.io"
+                docker login cp.icr.io --username cp --password $(params.ibm-entitlement-key)
               else
                 echo "techzone key - $(params.tz-ibm-entitlement-key)"
                 printf "$(params.tz-ibm-entitlement-key)" | tee $(results.key.path)
@@ -1174,25 +1177,21 @@ spec:
                     size: small  
                     state: removed 
             EOF
-    - name: delete-previous-job
+    - name: run-the-deployer
       taskRef:
         kind: Task
         name: ibm-pak
+      timeout: 6h0m0s
+      retries: 3
       runAfter:
         - configure-cloud-paks-services
       params:
         - name: SCRIPT
           value: |
             oc delete job cloud-pak-deployer -n $(params.namespace) --ignore-not-found
-    - name: run-the-deployer
-      taskRef:
-        kind: Task
-        name: ibm-pak
-      runAfter:
-        - delete-previous-job
-      params:
-        - name: SCRIPT
-          value: |
+
+            sleep 20
+
             oc apply -f - <<EOF
             apiVersion: batch/v1
             kind: Job
@@ -1247,16 +1246,9 @@ spec:
                     persistentVolumeClaim:
                       claimName: cloud-pak-deployer-status
             EOF
-    - name: wait-till-job-complete
-      timeout: 6h0m0s
-      taskRef:
-        kind: Task
-        name: ibm-pak
-      runAfter:
-        - run-the-deployer
-      params:
-        - name: SCRIPT
-          value: |
+
+            sleep 20
+
             while true
             do
               is_complete=$(oc get -n $(params.namespace) job/cloud-pak-deployer -o yaml | yq '.status.conditions.[] | select(.type == "Complete") | contains({"status": "'True'"})')
@@ -1266,5 +1258,14 @@ spec:
                 echo "Cloud Pak Deployer job is Complete."
                 break
               fi
+
+              did_fail=$(oc get -n $(params.namespace) job/cloud-pak-deployer -o yaml | yq '.status.conditions.[] | select(.type == "Failed") | contains({"status": "'True'"})')
+              if [[ $did_fail == "true" ]]; then
+                echo "Cloud Pak Deployer job failed."
+                echo $(oc get -n $(params.namespace) job/cloud-pak-deployer -o yaml | yq '.status.conditions.[] | select(.type == "Failed") | .reason)')
+                echo $(oc get -n $(params.namespace) job/cloud-pak-deployer -o yaml | yq '.status.conditions.[] | select(.type == "Failed") | .message)')
+                exit 68
+              fi
+              
               sleep 10
             done
